{{- if not .Values.keyVault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: kutcut
type: Opaque
stringData:
  # Base ConnectionString for API
  ConnectionStrings__PostgresConnectionString: {{ .Values.secret.postgresConnectionString | quote }}
  
  # JWT
  JwtSettings__SecretKey: {{ .Values.secret.jwtSecretKey | quote }}
  
  # RabbitMQ credentials
  RabbitMQ__UserName: {{ .Values.secret.rabbitmqUserName | quote }}
  RabbitMQ__Password: {{ .Values.secret.rabbitmqPassword | quote }}
  
  # Email settings
  EmailSettings__UserName: {{ .Values.secret.emailUserName | quote }}
  EmailSettings__Password: {{ .Values.secret.emailPassword | quote }}
  
  # Azure Storage
  AzureBlobStorage__ConnectionString: {{ .Values.secret.azureBlobConnectionString | quote }}
  
  # AuthService
  AuthService__BaseUrl: {{ .Values.secret.authServiceBaseUrl | quote }}
  
  # DB Migrations (legacy names if needed by migrator-job.yaml)
  POSTGRES_USER: {{ .Values.secret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
{{- end }}

