{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-kv
  namespace: kutcut
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    clientID: {{ .Values.keyVault.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: database-connection-string
          objectType: secret
          alias: ConnectionStrings__PostgresConnectionString
        - |
          objectName: JwtSettings--SecretKey
          objectType: secret
          alias: JwtSettings__SecretKey
        - |
          objectName: rabbitmq-username
          objectType: secret
          alias: RabbitMQ__UserName
        - |
          objectName: rabbitmq-password
          objectType: secret
          alias: RabbitMQ__Password
        - |
          objectName: email-user-name
          objectType: secret
          alias: EmailSettings__UserName
        - |
          objectName: email-password
          objectType: secret
          alias: EmailSettings__Password
        - |
          objectName: azure-blob-connection-string
          objectType: secret
          alias: AzureBlobStorage__ConnectionString
        - |
          objectName: auth-service-base-url
          objectType: secret
          alias: AuthService__BaseUrl
        - |
          objectName: postgres-user
          objectType: secret
          alias: POSTGRES_USER
        - |
          objectName: postgres-password
          objectType: secret
          alias: POSTGRES_PASSWORD
  secretObjects:
    - secretName: {{ .Release.Name }}-secret
      type: Opaque
      data:
        - objectName: database-connection-string
          key: ConnectionStrings__PostgresConnectionString
        - objectName: JwtSettings--SecretKey
          key: JwtSettings__SecretKey
        - objectName: rabbitmq-username
          key: RabbitMQ__UserName
        - objectName: rabbitmq-password
          key: RabbitMQ__Password
        - objectName: email-user-name
          key: EmailSettings__UserName
        - objectName: email-password
          key: EmailSettings__Password
        - objectName: azure-blob-connection-string
          key: AzureBlobStorage__ConnectionString
        - objectName: auth-service-base-url
          key: AuthService__BaseUrl
        - objectName: postgres-user
          key: POSTGRES_USER
        - objectName: postgres-password
          key: POSTGRES_PASSWORD
{{- end }}
