apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrator-job
  namespace: kutcut
  labels:
    app: migrator-kutcut
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyVault.clientId | quote }}