apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyVault.clientId | quote }}
