<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\soat.eleven.kutcut.domain\soat.eleven.kutcut.domain.csproj" />
    <ProjectReference Include="..\soat.eleven.kutcut.infra\soat.eleven.kutcut.infra.csproj" />
  </ItemGroup>

</Project>
