// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using soat.eleven.kutcut.infra.Context;

#nullable disable

namespace soat.eleven.kutcut.infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206022108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("soat.eleven.kutcut.infra.Models.NotificationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<int?>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("VideoId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("soat.eleven.kutcut.infra.Models.NotificationTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("notification_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Processado com sucesso"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Processado com erro"
                        });
                });

            modelBuilder.Entity("soat.eleven.kutcut.infra.Models.StatusModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Em processamento"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Processado com sucesso"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Processado com erro"
                        });
                });

            modelBuilder.Entity("soat.eleven.kutcut.infra.Models.VideoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("filename");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("varchar")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("soat.eleven.kutcut.infra.Models.NotificationModel", b =>
                {
                    b.HasOne("soat.eleven.kutcut.infra.Models.NotificationTypeModel", "TypeNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_type");

                    b.HasOne("soat.eleven.kutcut.infra.Models.VideoModel", "Video")
                        .WithMany("Notifications")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_video_id");

                    b.Navigation("TypeNavigation");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("soat.eleven.kutcut.infra.Models.VideoModel", b =>
                {
                    b.HasOne("soat.eleven.kutcut.infra.Models.StatusModel", "StatusNavigation")
                        .WithMany("Videos")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_videos_status");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("soat.eleven.kutcut.infra.Models.NotificationTypeModel", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("soat.eleven.kutcut.infra.Models.StatusModel", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("soat.eleven.kutcut.infra.Models.VideoModel", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
